repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-json
  - id: check-yaml
    args:
     - --unsafe

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: ed81924a8b1cecdaa570b072528fa80c9c4d6ccd  # frozen: 0.37.1
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
    - id: check-dependabot

- repo: https://github.com/brokenpip3/pre-commit-hooks
  rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
  hooks:
    - id: github-actions-hash
      files: ^.github/workflows/.*\.(yml|yaml)$ # limit only to github workflo
