name: update-pre-commit-hooks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@24b7a510db4356b7cb0a2d0b8f72d1226fa7195b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
