name: update-pre-commit-hooks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@24b7a510db4356b7cb0a2d0b8f72d1226fa7195b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
